BUG 9006 "The changes made by process supervisors to fields in..." SOLVED
- The changes made by process supervisors to fields in DynaForms are not recorded in the Change Log

- Changes made by process supervisors to fields in DynaForms, may be viewed by a user if this is defined in "process permissions". with this the user will see the "Change Log" of a case.
- Additionally the following error was corrected:
  > Fatal error: Call to undefined method Ajax::dynaformViewFromHistory() in processmaker/workflow/engine/methods/cases/ajaxListener.php on line 42

  > The error was corrected by adding code to complete the "Change Log" in the option "View"